# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = false

# Setting Time out
command_timeout = 10000

# Change the default prompt format
format = """\
$env_var\
$all$character"""

# Change the default prompt format
#format = """\
#(238)$env_var\
#$all(238)$character"""

# Change the default prompt characters
[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold)'  # removed space between distro and rest for pwsh
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
format = "[$user]($style) "
disabled = false  # disable in powershell
show_always = true

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only = "  "
format = "at [$path]($style)[$read_only](bold) "

[git_branch]
symbol = " "
format = "on [$symbol$branch](bold) "
truncation_length = 4
truncation_symbol = "…/"

[git_status]
format = '[\($all_status$ahead_behind\)](bold) '
conflicted = " "
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)]'
renamed = "襁 "
deleted = " "

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
ssh_symbol = '󰣀'
disabled = false

[docker_context]
format = "via [$symbol$context](bold) "
symbol = " "
style = "bold"

[c]
format = "via [$symbol$context](bold) "
symbol = " "
style = "bold"

#[cpp]
#format = "via [ $version](bold) "

#[csharp]
#format = "via [ $version](bold) "

[dotnet]
format = "via [$symbol$context](bold) "
symbol =" "
style = "bold"
 
[golang]
format = "via [$symbol$context](bold) "
symbol = " "
style = "bold"
 
[nodejs]
format = "via [$symbol$context](bold) "
symbol = " "
style = "bold"

[python]
symbol = " "
python_binary = "python3"
style = "bold"

[rust]
symbol = " "
style = "bold"

[terraform]
format = "via [$symbol](bold) 壟 [$workspace](bold) "
symbol = "󱁢 "

[kubernetes]
format = 'on [$symbol$context\($namespace\)](bold) '
symbol = " "
style = "bold"
disabled = false