version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '{{ env "PC_DISTRO" }}'
    background = 'transparent'
    foreground = 'p:blue'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = '<b>{{ .UserName }}</b> '
    background = 'transparent'
    foreground = 'p:blue'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = '{{ if .SSHSession }}in {{ end }}<p:blue><b>{{ if .SSHSession }} {{ end }}</b></>'
    background = 'transparent'
    foreground = 'p:white'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = 'at <p:blue><b>{{if eq .Path "~" }}󰋜 {{ end }}{{ path .Path .Location }}</b></> '
    background = 'transparent'
    foreground = 'p:white'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']
    template = 'on {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    background = 'transparent'
    foreground = 'p:white'

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    template = '  '
    background = 'transparent'
    foreground = 'p:white'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 500
      style = 'roundrock'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

  [[blocks]]
    type = 'rprompt'
    overflow = 'hidden'

    [[blocks.segments]]
      type = 'executiontime'
      style = 'plain'
      foreground = 'yellow'
      background = 'transparent'
      template = '{{ .FormattedMs }}'

      [blocks.segments.properties]
        threshold = 500
        style = 'roundrock'

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
